### ISSUE TITLE
Message won't sent

### ISSUE THREAD

**Issue by Bukk94** [taksan/skype-java-api#81]
Hello I guess this api is outdated because I'm trying to send a message but it'll get stuck and it won't send. Basically the same as here: https://github.com/taksan/skype-java-api/issues/78
I have normal chat, not group or something just regular chat and it won't work either. 
There is attached picture. Take a look.
![wrkv](https://cloud.githubusercontent.com/assets/3464841/16943177/98cde8fe-4d9a-11e6-8aba-62576196d0fc.png)

And my problem described more here: http://stackoverflow.com/questions/38452928/java-skype-api-wont-send-messages

Any suggestions what I did wrong or what could be wrong on this api?

**Comment by TestobjektX** [comment]
I've the Same issue since yesterday afternoon...

**Comment by taksan** [comment]
The desktop api is deprecated and that's why I actually dropped support on this project and haven't worked on any of the issues.

But anyway, I'll take a look and check if it's a simple fix. If so, I'll fix it

**Comment by Bukk94** [comment]
Thank you!

**Comment by taksan** [comment]
The latest version is the code. I didn't release other versions. 
I worked only on Java API, I wasn't even aware there was a C# api

**Comment by taksan** [comment]
Ok. Let's get some info. When you use the skype client to send the messages, does it work normally? Do you witness this problem only when the message is sent by the api?

**Comment by taksan** [comment]
Ok. Let's get some info. When you use the skype client to send the messages, does it work normally? Do you witness this problem only when the message is sent by the api?

**Comment by taksan** [comment]
What's the skype version and on which operating system?

**Comment by Bukk94** [comment]
I have no problems sending it myself. It works normally. When the message is sent through the api, it won't send (picture above). I tried to wait (my theory was that skype needed to process it in the client) but after 2 hours it was still stucked on 'not sent yet'.
I'm using Windows 7 x64 Ultimate with Skype version 7.26.0.101

**Comment by taksan** [comment]
I'll try to debug, but it looks like they broke the desktop api in this new version.

**Comment by ML1** [comment]
ChatMessageListener interface's chatMessageReceived and chatMessageSent methods not working as expected.

**Comment by Bukk94** [comment]
Did you find anything? @taksan

**Comment by the7thobserver** [comment]
Where do you see that the desktop api is deprecated?

**Comment by taksan** [comment]
@the7thobserver 
Alright, it was a long time ago since I last saw that the desktop api would be discontinued. It looks like they changed their mind and won't be discontinuing it completely, according with the following blog post:

https://blogs.skype.com/2013/11/06/feature-evolution-and-support-for-the-skype-desktop-api/

```
Previously we shared that we would retire the Desktop API later this year. However, I’m happy to share that we will be extending support for two of the most widely used features – call recording and compatibility with hardware devices – until we determine alternative options or retire the current solution. Although chat via third party applications, will cease to work as previously communicated
```

Besides, to complement, here's some other info:

https://support.skype.com/en/faq/FA214/what-is-the-desktop-api

```
Important: As communicated in this blog post, due to technology improvements we are making to the Skype experience, some features of the API will stop working with Skype for desktop. For example, delivery of chat messages using the API will cease to work.
```

So, what you are witnessing now is precisely what they already announced. Therefore, this is not an issue of the api, but simply the fact that skype is dropping down support for message delivery,

Taking this into account, I'm closing this issue. I'm sorry guys, and thanks for all the interest in the api. I was really sad when they announced it would be discontinued, and even though they still didn't finish it off completely by now, it is already crippled.
